// Generated by CoffeeScript 1.6.3
define(function() {
  'use strict';
  return function(match) {
    match('', 'home#show');
    return match('photo/:id', 'home#photo', {
      constraints: {
        id: /^[0-9]*$/
      }
    });
  };
});
