// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['views/base/view', 'text!templates/header.html!strip'], function(View, template) {
  var HeaderView, _ref;
  return HeaderView = (function(_super) {
    __extends(HeaderView, _super);

    /*
    autorender: true
    classname: 'header'
    id: 'header'
    region: 'header'
    tagName: 'header'
    template: template
    
    listen:
      'loginStatus mediator': 'render'
    */


    function HeaderView() {
      _ref = HeaderView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return HeaderView;

  })(View);
});
