// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model'], function(Chaplin, Model) {
  'use strict';
  var PhotosModel, _ref;
  return PhotosModel = (function(_super) {
    __extends(PhotosModel, _super);

    function PhotosModel() {
      _ref = PhotosModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PhotosModel.prototype.urlRoot = "http://api.flickr.com/services/rest/?method=flickr.photos.getInfo&api_key=afbc4a16eae358578189479ffae8c063&photo_id=cat&format=json&nojsoncallback=1&api_sig=65a41067f4e207282d023619e6a015a";

    PhotosModel.prototype.defaults = {
      message: 'ey!'
    };

    return PhotosModel;

  })(Model);
});
