// Generated by CoffeeScript 1.6.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['chaplin', 'models/base/model', 'config'], function(Chaplin, Model, Config) {
  'use strict';
  var PhotoComment, _ref;
  return PhotoComment = (function(_super) {
    __extends(PhotoComment, _super);

    function PhotoComment() {
      _ref = PhotoComment.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return PhotoComment;

  })(Model);
});
